apiVersion: v1
kind: Pod
metadata:
  name: mysite
  labels:
    function: webserver
spec:
  containers:
  - name: httpd
    image: ghcr.io/malonzo1/hello-world:milestone-4.6
    ports:
    - containerPort: 80
    env:
    - name: SECRET_KEY
      value: "mysecretkey"
    - name: PORT
      value: "80"
