apiVersion: v1
kind: Pod
metadata:
  name: mysite
  labels:
    function: webserver
spec:
  containers:
  - name: httpd
    image: ghcr.io/malonzo1/hello-world:milestone-5.0
    ports:
    - containerPort: 80
    env:
    - name: SECRET_KEY
      value: "mysecretkey"
    - name: PORT
      value: "80"
    - name: DB_NAME
      value: "mysite"
    - name: DB_USER
      value: "postgres"
    - name: DB_PASSWORD
      value: "django"   
    - name: DB_HOST
      value: "postgres"
    resources:
      requests:
        memory: "512Mi"
        cpu: "250m"
      limits:
        memory: "900Mi"
        cpu: "1000m"  
    livenessProbe:
      httpGet:
        path: /polls/
        port: 80
      initialDelaySeconds: 30
      periodSeconds: 60

                         

